role: follower
model: # define the net of vFL party
  train_net:
    name: follower_loss_net
    inputs:
      - name: id_hldr0
        source: local
      - name: wt_hldr0
        source: local
    outputs:
      - name: wide_embedding
        destination: remote
      - name: deep_embedding
        destination: remote
      - name: l2_regu
        destination: local
  eval_net:
    name: follower_net
    inputs:
      - name: id_hldr0
        source: local
      - name: wt_hldr0
        source: local
    outputs:
      - name: wide_embedding
        destination: remote
      - name: deep_embedding
        destination: remote
opts: # define ms optimizer
  - type: FTRL
    grads: # define ms grad operation
      - inputs:
          - name: id_hldr0
          - name: wt_hldr0
        output:
          name: wide_embedding
        sens: wide_loss
    params:
      - name: wide
    hyper_parameters:
      learning_rate: 5.e-2
      l1: 1.e-8
      l2: 1.e-8
      initial_accum: 1.0
      loss_scale: 1024.0
  - type: Adam
    grads:
      - inputs:
          - name: id_hldr0
          - name: wt_hldr0
        output:
          name: deep_embedding
        sens: deep_loss
      - inputs:
          - name: id_hldr0
          - name: wt_hldr0
        output:
          name: l2_regu
        sens: 1024.0
    params:
      - name: deep
      - name: dense
    hyper_parameters:
      learning_rate: 3.5e-4
      eps: 1.e-8
      loss_scale: 1024.0
dataset:
  name: criteo
  features:
    - id_hldr0
    - wt_hldr0
hyper_parameters:
  epochs: 20
  batch_size: 16000
  is_eval: True
ckpt_path: ./checkpoints