role: leader
model: # define the net of vFL party
  train_net:
    name: leader_loss_net
    inputs:
      - name: leader_wide_embedding
        source: local
      - name: leader_deep_embedding
        source: local
      - name: follower_wide_embedding
        source: remote
      - name: follower_deep_embedding
        source: remote
      - name: label
        source: local
    outputs:
      - name: out
        destination: local
      - name: loss
        destination: local
  eval_net:
    name: leader_eval_net
    inputs:
      - name: leader_wide_embedding
        source: local
      - name: leader_deep_embedding
        source: local
      - name: follower_wide_embedding
        source: remote
      - name: follower_deep_embedding
        source: remote
    outputs:
      - name: logits
        destination: local
      - name: pred_probs
        destination: local
    gt: label
opts: # define ms optimizer
  - type: Adam
    grads:
      - inputs:
          - name: leader_wide_embedding
          - name: leader_deep_embedding
          - name: follower_wide_embedding
          - name: follower_deep_embedding
          - name: label
        output:
          name: loss
        sens: 1024.0
    params:
      - name: deep
      - name: dense
    hyper_parameters:
      learning_rate: 3.5e-4
      eps: 1.e-8
      loss_scale: 1024.0
grad_scalers: # define the grad scale calculator
  - inputs:
      - name: leader_wide_embedding
      - name: leader_deep_embedding
      - name: follower_wide_embedding
      - name: follower_deep_embedding
    output:
      name: loss
    sens: 1024.0
dataset:
  name: criteo
  features:
    - id_hldr
    - wt_hldr
  labels:
    - ctr
hyper_parameters:
  epochs: 20
  batch_size: 16000
  is_eval: True
ckpt_path: ./checkpoints
privacy:
  label_dp:
    eps: 1.0