role: leader
model: # define the net of vFL party
  train_net:
    name: leader_loss_net
    inputs:
      - name: id_hldr
        source: local
      - name: wt_hldr
        source: local
    outputs:
      - name: leader_wide_embedding
        destination: remote
      - name: leader_deep_embedding
        destination: remote
      - name: leader_l2_regu
        destination: local
  eval_net:
    name: leader_net
    inputs:
      - name: id_hldr
        source: local
      - name: wt_hldr
        source: local
    outputs:
      - name: leader_wide_embedding
        destination: remote
      - name: leader_deep_embedding
        destination: remote
opts: # define ms optimizer
  - type: FTRL
    grads: # define ms grad operations
      - inputs:
          - name: id_hldr
          - name: wt_hldr
        output:
          name: leader_wide_embedding
        sens: tee_embedding
    params:
      - name: wide
    hyper_parameters:
      learning_rate: 5.e-2
      l1: 1.e-8
      l2: 1.e-8
      initial_accum: 1.0
      loss_scale: 1024.0
  - type: Adam
    grads:
      - inputs:
          - name: id_hldr
          - name: wt_hldr
        output:
          name: leader_deep_embedding
        sens: tee_embedding
      - inputs:
          - name: id_hldr
          - name: wt_hldr
        output:
          name: leader_l2_regu
        sens: 1024.0
    params:
      - name: deep
      - name: dense
    hyper_parameters:
      learning_rate: 3.5e-4
      eps: 1.e-8
      loss_scale: 1024.0
dataset:
  name: criteo
  features:
    - id_hldr
    - wt_hldr
hyper_parameters:
  epochs: 20
  batch_size: 16000
  is_eval: True
ckpt_path: ./checkpoints
