# communicator
http_server_address: "127.0.0.1:1086"
remote_server_address: "127.0.0.1:1087"

# ==============================================================================
# data join
raw_dataset_dir: "./datasets/input/leader/"
raw_eval_dataset_dir: "./datasets/input/leader/"
dataset_dir: "./datasets/output/leader/"
eval_dataset_dir: "./datasets/output/leader/"
data_schema_path: "./yaml_files/leader_schema.yaml"
primary_key: "oaid"
bucket_num: 5
store_type: "csv"
shard_num: 1
join_type: "psi"
thread_num: 0

# ==============================================================================
data_path: "./mindrecord/"
device_target: GPU
# regular yaml files
follower_bottom_yaml_path: './yaml_files/follower_bottom.yaml'
leader_bottom_yaml_path: './yaml_files/leader_bottom.yaml'
leader_top_yaml_path: './yaml_files/leader_top.yaml'

# yaml files involving tee
follower_bottom_tee_yaml_path: './yaml_files/follower_bottom_tee.yaml'
leader_bottom_tee_yaml_path: './yaml_files/leader_bottom_tee.yaml'
leader_tee_yaml_path: './yaml_files/leader_tee.yaml'
leader_top_tee_yaml_path: './yaml_files/leader_top_tee.yaml'

# ==============================================================================
# argparse_init 'WideDeep'
epochs: 15
full_batch: False
batch_size: 16000
field_size: 39
leader_field_size: 20
follower_field_size: 19
vocab_size: 200000
vocab_cache_size: 0
emb_dim: 80
deep_layer_dim: [1024, 512, 256, 128]
deep_layer_act: "relu"
keep_prob: 1.0
dropout_flag: False
ckpt_path: "./ckpt"
host_device_mix: 0
dataset_type: "mindrecord"
parameter_server: 0
field_slice: False
sparse: False
deep_table_slice_mode: "column_slice"
enable_TEE: False

# WideDeepConfig
weight_bias_init: ["normal", "normal"]
emb_init: "normal"
init_args: [-0.01, 0.01]
l2_coef: 8.e-5
manual_shape: None

# retrain
resume: False
pre_trained_follower_bottom: ""
pre_trained_leader_bottom: ""
pre_trained_leader_tee: ""
pre_trained_leader_top: ""

# privacy
label_dp: False
embedding_tee: False
simu_tee: False