role: follower
model: # define the net of vFL party
  train_net:
    name: leader_loss_net
    inputs:
      - name: embedding_table
        source: remote
        compress_type: min_max
        bit_num: 6
      - name: attention_mask
        source: remote
        compress_type: bit_pack
        bit_num: 1
    outputs:
      - name: hidden_states
        destination: remote
        compress_type: min_max
        bit_num: 6
  eval_net:
    name: leader_eval_net
    inputs:
      - name: embedding_table
        source: remote
        compress_type: min_max
        bit_num: 6
      - name: word_table
        source: remote
        compress_type: min_max
        bit_num: 6
      - name: input_ids
        source: remote
      - name: current_index
        source: local
    outputs:
      - name: log_probs
        destination: local
    gt: label
opts: # define ms optimizer
  - type: CustomizedAdam
    grads:
      - inputs:
          - name: embedding_table
          - name: attention_mask
        output:
          name: hidden_states
        sens: output
    params:
      - name: backbone
    hyper_parameters:
      learning_rate: 5.e-6
      eps: 1.e-8
      loss_scale: 1024.0
grad_scalers: # define the grad scale calculator
  - inputs:
      - name: embedding_table
      - name: attention_mask
    output:
      name: hidden_states
    sens: output
dataset:
  name: wiki
  features:
    - input_ids
    - position_id
    - attention_mask
hyper_parameters:
  epochs: 20
  batch_size: 2
  is_eval: False
ckpt_path: ./checkpoints