role: follower
model: # define the net of vFL party
  train_net:
    name: follower_loss_net
    inputs:
      - name: input_ids
        source: local
      - name: position_id
        source: local
      - name: attention_mask
        source: local
    outputs:
      - name: embedding_table
        destination: remote
        compress_type: min_max
        bit_num: 6
      - name: word_table
        destination: local
      - name: attention_mask
        destination: remote
        compress_type: bit_pack
        bit_num: 1
  eval_net:
    name: follower_net
    inputs:
      - name: input_ids
        source: local
      - name: position_id
        source: local
      - name: attention_mask
        source: local
    outputs:
      - name: embedding_table
        destination: remote
        compress_type: min_max
        bit_num: 6
opts: # define ms optimizer
  - type: CustomizedAdam
    grads:
      - inputs:
          - name: input_ids
          - name: position_id
          - name: attention_mask
        output:
          name: embedding_table
        sens: hidden_states
      - inputs:
          - name: input_ids
          - name: position_id
          - name: attention_mask
        output:
          name: word_table
        sens: output
    params:
      - name: word_embedding
      - name: position_embedding
    hyper_parameters:
      learning_rate: 5.e-6
      eps: 1.e-8
      loss_scale: 1024.0
dataset:
  name: wiki
  features:
    - input_ids
    - position_id
    - attention_mask
hyper_parameters:
  epochs: 20
  batch_size: 2
  is_eval: False
ckpt_path: ./checkpoints
privacy:
  embedding_dp:
    eps: 5.0