role: leader
model: # define the net of vFL party
  train_net:
    name: leaderhead_loss_net
    inputs:
      - name: hidden_states
        source: remote
        compress_type: min_max
        bit_num: 6
      - name: input_ids
        source: local
      - name: word_table
        source: remote
        compress_type: min_max
        bit_num: 6
      - name: position_id
        source: local
      - name: attention_mask
        source: local
    outputs:
      - name: output
        destination: local
  eval_net:
    name: leader_eval_net
    inputs:
      - name: hidden_states
        source: remote
        compress_type: min_max
        bit_num: 6
      - name: input_ids
        source: remote
      - name: word_table
        source: remote
        compress_type: min_max
        bit_num: 6
      - name: position_id
        source: remote
      - name: attention_mask
        source: remote
        compress_type: bit_pack
        bit_num: 1
    outputs:
      - name: log_probs
        destination: local
    gt: input_ids
opts: # define ms optimizer
  - type: CustomizedAdam
    grads:
      - inputs:
          - name: hidden_states
          - name: input_ids
          - name: word_table
          - name: position_id
          - name: attention_mask
        output:
          name: output
        sens: 1024.0
    params:
      - name: top_query_layer
    hyper_parameters:
      learning_rate: 5.e-6
      eps: 1.e-8
      loss_scale: 1024.0
grad_scalers: # define the grad scale calculator
  - inputs:
      - name: hidden_states
      - name: input_ids
      - name: word_table
      - name: position_id
      - name: attention_mask
    output:
      name: output
    sens: 1024.0
dataset:
  name: wiki
  features:
    - input_ids
    - position_id
    - attention_mask
hyper_parameters:
  epochs: 20
  batch_size: 2
  is_eval: False
ckpt_path: ./checkpoints